### ISSUE TITLE
Why is -p false in run-assembly-visualizer.sh 

### ISSUE THREAD

**Issue by mictadlo** [phasegenomics/juicebox_scripts#11]
Hi,
Is there any reason why `-p false` is set in `run-assembly-visualizer.sh`?

Thank you in advance,

Michal

**Comment by maximilianpress** [comment]
Hi Michal, 
I am not sure but it is a good question. I am seeing if I can track down why that flag is set, we will update when we know.

Thanks, Max

**Comment by zeeev** [comment]
Hi @mictadlo,

The -p was set to false because gnu parallel wasn't installed on my computer when i developed the scripts.

--Zev

**Comment by mictadlo** [comment]
Ok, Thank you.
