### ISSUE TITLE
juicebox to chromosome bins fasta

### ISSUE THREAD

**Issue by mictadlo** [phasegenomics/juicebox_scripts#12]
Hi, 
I loaded my 3d-dna output into `JuiceBox` and the contact matrix shows the 19 chromosomes. How can I create a FASTA file which contains only 19 entries?

Thank you in advance,

Michal

**Comment by shawnpg** [comment]
Hi Michal,

The scripts here don't have the ability to output only chromosomes as an option, but you can make them do that by editing your .assembly file by hand. The .assembly file has two main sections: (1) in the top half of the file, a list of contigs in the assembly along with some stats, and (2) a list of the contigs as arranged on the scaffolds, one scaffold per line. If you delete all of the entries in (2) following the 19 scaffolds, the juicebox_assembly_converter.py will generate a FASTA with just the 19 chromosomes.

Thanks,

Shawn

**Comment by mictadlo** [comment]
Hi Shawn,
My .FINAL.assembly might looks a little different [QMg_NbQ4P_RN.FINAL.assembly.txt](https://github.com/phasegenomics/juicebox_scripts/files/2725382/QMg_NbQ4P_RN.FINAL.assembly.txt).

Could you please point to me where section 1 and 2 starts?

Thank you in advance.

Michal

**Comment by shawnpg** [comment]
Hi Michal,

Section 1 includes all the lines that begin with a ">". Everything that follows is section 2; all of those lines should only include whitespace-delimited numbers. That starts on line 2387 in the file you attached. Also, I went ahead and just deleted all the extra lines so you only have the 19 chromosomes in the attached. There were a few other lines that looked like scaffolds, but they look very small so if you only want the things that made it onto chromosomes they are probably safe to discard.

Thanks,

Shawn
[QMg_NbQ4P_RN.FINAL.chr_only.assembly.txt](https://github.com/phasegenomics/juicebox_scripts/files/2725422/QMg_NbQ4P_RN.FINAL.chr_only.assembly.txt)

**Comment by mictadlo** [comment]
Hi Shawn,
Thank you for doing it. Unfortunately, I ran into this error:
```
Processing assembly file. Details:
Assembly:       QMg_NbQ4P_RN.FINAL.chr_only.assembly
Fasta:          QMg_NbQ4P_RN.FINAL.fasta
Output prefix:  QMg_NbQ4P_RN.FINAL.chr_only
Contig mode:    False

Reading sequences from QMg_NbQ4P_RN.FINAL.fasta...
...................................
Sequences read

Reading .assembly file QMg_NbQ4P_RN.FINAL.chr_only.assembly...
Traceback (most recent call last):
  File "/work/waterhouse_team/apps/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 727, in <module>
    verbose=verbose)
  File "/work/waterhouse_team/apps/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 77, in process
    assembly_map, scaffolds = self._read_assembly(assembly, contig_mode=contig_mode)
  File "/work/waterhouse_team/apps/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 208, in _read_assembly
    unscaffolded_contigs.remove(assembly_map[index][0])
ValueError: list.remove(x): x not in list
```

with this command `juicebox_assembly_converter.py -a QMg_NbQ4P_RN.FINAL.chr_only.assembly -f QMg_NbQ4P_RN.FINAL.fasta`.

Thank you in advance,

Michal

**Comment by maximilianpress** [comment]
This was open for a long time. I checked the .assembly file linked and it contained the `hic_gap` contig that is repeated. This is a new thing that appears in some newer juicebox versions that breaks our script. (We make the assumption that no contig is repeated, and the gap is used between every contig in a scaffold.) We previously addressed this in this issue: https://github.com/phasegenomics/juicebox_scripts/issues/24. 

We now include the `juicebox_scripts/degap_assembly.py` script that can be used to remove this feature from the .assembly file. Run this on your assembly file and use the output for `juicebox_assembly_converter.py`.

Thanks, Max
