### ISSUE TITLE
juicebox assembly converter no longer working

### ISSUE THREAD

**Issue by aboyher** [phasegenomics/juicebox_scripts#16]
I believe the naming convention has changed for the assembly files. I'm getting this error 

> Processing assembly file. Details:
> Assembly:       tme7_v0.6jb_1_reducedN.final.review.assembly
> Fasta:          ../../tme7_v0.6jb_1_reducedN.fa
> Output prefix:  tme7_v0.6jb_1_reducedN.review.converted
> Contig mode:    True
> 
> Reading sequences from ../../tme7_v0.6jb_1_reducedN.fa...
> .
> Sequences read
> 
> Reading .assembly file tme7_v0.6jb_1_reducedN.final.review.assembly...
> .assembly read
> 
> Checking for breaks listed in .assembly and making them...
> Traceback (most recent call last):
>   File "/home/aboyher/src/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 799, in <module>                                                                           
>     verbose=verbose)
>   File "/home/aboyher/src/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 82, in process                                                                             
>     sequences = self._add_breaks(sequences, assembly_map)
>   File "/home/aboyher/src/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 242, in _add_breaks                                                                        
>     assembly_map.sort(key=functools.cmp_to_key(cmp_assembly_map_entries))
>   File "/usr/lib64/python2.7/functools.py", line 87, in __lt__
>     return mycmp(self.obj, other.obj) < 0
>   File "/home/aboyher/src/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 275, in cmp_assembly_map_entries                                                           
>     names1 = extract_contig_info(frag1[0])
>   File "/home/aboyher/src/juicebox_scripts/juicebox_scripts/juicebox_assembly_converter.py", line 311, in extract_contig_info                                                                
>     names["index"] = int(frag_fields[-1].replace("fragment_", ""))
> ValueError: invalid literal for int() with base 10: 'HiC_scaffold_4039_obj'

And there are plenty of lines like this one in my review assembly file: 

> >HiC_scaffold_4396_obj:::debris 8064 15175
> >HiC_scaffold_2535_obj:::debris 8070 15151
> >HiC_scaffold_2741_obj:::debris 8074 15135

**Comment by shawnpg** [comment]
Hi,

Can you confirm what version of Juicebox you are using? I checking in version 1.9.8 and the naming convention appears to be the same.

Also, just to make sure, was there any other tool besides juicebox which might have introduced the :::debris tags? The current code assumes those are only introduced by Juicebox when misjoined contigs are broken.

Thanks!

**Comment by maximilianpress** [comment]
Hi Adam, thanks for letting us know. 

If that is from your assembly file, it does look like maybe their format changed. That is an odd change for them to make because if two breaks are made in the same contig, it will generate two debris contigs with identical names without a good way to map back to coordinates in the original contig. If the debris contigs were of different sizes that would also possibly frameshift the non-debris fragments.

Can you tell us which version of juicebox you're using, and share your .assembly file?

Our tools work with Juicebox up to v1.9.8 for certain. 
Thanks, Max

**Comment by aboyher** [comment]
I'm on 1.9.1. I thought for sure i was on the latest version though, i'm not sure how that happened. I will try again with the newer version.

**Comment by maximilianpress** [comment]
Closing this as it's been open for a long time without updates, and appears to have been resolved with the juicebox update.
