### ISSUE TITLE
makeAgpFromFasta.py indentation

### ISSUE THREAD

**Issue by rwhetten** [phasegenomics/juicebox_scripts#2]
Lines 30 and 31 contain a mix of tab and space characters (in the version downloaded as a zip archive) that causes an error: "IndentationError: expected an indented block"
Changing the indentation to all spaces prevents the error, but the script still wouldn't run until I commented out the test for the number of command line arguments.
 	if len(sys.argv) != 2:
    	printUsage()
	    sys.exit()

**Comment by maximilianpress** [comment]
Thanks for catching those bugs- they should be fixed in the most recent commit on this branch.
Thanks, max
