### ISSUE TITLE
Using Juicer 1.11 output will not convert

### ISSUE THREAD

**Issue by Hannah1746** [phasegenomics/juicebox_scripts#31]
python juicebox_assembly_converter.py -a kraken.final.review.assembly -f curated.fasta 
Processing assembly file. Details:
Assembly:			kraken.final.review.assembly
Fasta:				curated.fasta
Output prefix:			kraken.final.review
Contig mode:			False
Simple Chromosome Names:	False

Reading sequences from curated.fasta...
......
Sequences read

Reading .assembly file Gyro_kraken.final.review.assembly...
Traceback (most recent call last):
  File "juicebox_assembly_converter.py", line 831, in <module>
    processed_assembly = JuiceboxConverter().process(fasta, assembly,
  File "juicebox_assembly_converter.py", line 78, in process
    assembly_map, scaffolds = self._read_assembly(assembly, contig_mode=contig_mode)
  File "juicebox_assembly_converter.py", line 193, in _read_assembly
    raise ZeroLengthContigError('Assembly {0} lists contig {1} as zero length'.format(assembly, tokens[0]))
__main__.ZeroLengthContigError: Assembly kraken.final.review.assembly lists contig utg000577l_pilon_pilon:::fragment_1:::debris as zero length

**Comment by shawnpg** [comment]
Hi, thanks for reporting this issue. This exception is raised when one of the contigs (utg000577l_pilon_pilon:::fragment_1:::debris in this case) is listed as having zero length in the assembly file. A couple questions so we can investigate:

1. Can you share kraken.final.review.assembly so we can see what is in the assembly file?
2. What version of Juicebox are you using?

Thanks,

Shawn

**Comment by Hannah1746** [comment]
Hey Shawn,

Thank you for the fast response. I am using 1.11.08 and here is the file:
>utg000072l_pilon_pilon:::fragment_1 1 947083
>utg000072l_pilon_pilon:::fragment_2:::debris 2 250000
>utg000072l_pilon_pilon:::fragment_3 3 8978841
>utg000035l_pilon_pilon 4 10172762
>utg000073l_pilon_pilon 5 9128135
>utg000114l_pilon_pilon 6 8990579
>utg000032l_pilon_pilon 7 8531206
>utg000031l_pilon_pilon 8 8468168
>utg000088l_pilon_pilon 9 7785032
>utg000052l_pilon_pilon 10 7324498
>utg000049l_pilon_pilon 11 7300801
>utg000056l_pilon_pilon 12 7220493
>utg000116l_pilon_pilon 13 6749770
>utg000034l_pilon_pilon 14 6719493
>utg000047l_pilon_pilon 15 6614429
>utg000036l_pilon_pilon 16 5986601
>utg000209l_pilon_pilon 17 5693727
>utg000053l_pilon_pilon 18 5553057
>utg000005l_pilon_pilon 19 5458868
>utg000059l_pilon_pilon 20 5457622
>utg000198l_pilon_pilon 21 5394399
>utg000066l_pilon_pilon 22 5037104
>utg000016l_pilon_pilon 23 4952001
>utg000147l_pilon_pilon 24 4849615
>utg000058l_pilon_pilon 25 4766433
>utg000033l_pilon_pilon 26 4653006
>utg000020l_pilon_pilon:::fragment_1 27 586189
>utg000020l_pilon_pilon:::fragment_2:::debris 28 250000
>utg000020l_pilon_pilon:::fragment_3 29 3573934
>utg000024l_pilon_pilon 30 4259163
>utg000091l_pilon_pilon 31 4140201
>utg000111l_pilon_pilon 32 4126446
>utg000104l_pilon_pilon 33 4123134
>utg000069l_pilon_pilon 34 4020583
>utg000181l_pilon_pilon 35 3858779
>utg000051l_pilon_pilon 36 3832816
>utg000004l_pilon_pilon 37 3772311
>utg000107l_pilon_pilon 38 3751367
>utg000007l_pilon_pilon:::fragment_1 39 420416
>utg000007l_pilon_pilon:::fragment_2:::debris 40 125000
>utg000007l_pilon_pilon:::fragment_3 41 3147373
>utg000001l_pilon_pilon 42 3539165
>utg000202l_pilon_pilon 43 3436644
>utg000159l_pilon_pilon:::fragment_1 44 2641214
>utg000159l_pilon_pilon:::fragment_2:::debris 45 250000
>utg000159l_pilon_pilon:::fragment_3 46 487592
>utg000232l_pilon_pilon 47 3249361
>utg000206l_pilon_pilon 48 3069021
>utg000067l_pilon_pilon 49 3031806
>utg000185l_pilon_pilon 50 2921982
>utg000161l_pilon_pilon 51 2883603
>utg000026l_pilon_pilon 52 2857018
>utg000117l_pilon_pilon 53 2830458
>utg000019l_pilon_pilon 54 2827638
>utg000003l_pilon_pilon 55 2757512
>utg000248l_pilon_pilon 56 2717639
>utg000290l_pilon_pilon 57 2661953
>utg000289l_pilon_pilon 58 2628840
>utg000113l_pilon_pilon 59 2519007
>utg000027l_pilon_pilon 60 2499284
>utg000062l_pilon_pilon 61 2496818
>utg000283l_pilon_pilon 62 2369195
>utg000183l_pilon_pilon 63 2301597
>utg000210l_pilon_pilon 64 2279649
>utg000101l_pilon_pilon 65 2275278
>utg000095l_pilon_pilon 66 2274885
>utg000272l_pilon_pilon 67 2274050
>utg000280l_pilon_pilon 68 2245660
>utg000108l_pilon_pilon 69 2230320
>utg000200l_pilon_pilon 70 2201383
>utg000256l_pilon_pilon 71 2180407
>utg000115l_pilon_pilon 72 2126713
>utg000139l_pilon_pilon 73 2060181
>utg000295l_pilon_pilon 74 2025081
>utg000180l_pilon_pilon 75 1987048
>utg000140l_pilon_pilon 76 1971958
>utg000284l_pilon_pilon 77 1959029
>utg000011l_pilon_pilon 78 1945724
>utg000112l_pilon_pilon 79 1908868
>utg000044l_pilon_pilon 80 1898027
>utg000028l_pilon_pilon 81 1845995
>utg000022l_pilon_pilon 82 1830533
>utg000074l_pilon_pilon 83 1810101
>utg000207l_pilon_pilon 84 1805929
>utg000061l_pilon_pilon 85 1780134
>utg000273l_pilon_pilon 86 1752780
>utg000075l_pilon_pilon 87 1744443
>utg000335l_pilon_pilon 88 1738438
>utg000097l_pilon_pilon 89 1733225
>utg000249l_pilon_pilon 90 1727345
>utg000054l_pilon_pilon 91 1714381
>utg000203l_pilon_pilon 92 1695753
>utg000223l_pilon_pilon 93 1656384
>utg000055l_pilon_pilon 94 1649782
>utg000230l_pilon_pilon 95 1613328
>utg000293l_pilon_pilon 96 1594386
>utg000094l_pilon_pilon 97 1594060
>utg000078l_pilon_pilon 98 1582886
>utg000105l_pilon_pilon 99 1567195
>utg000029l_pilon_pilon 100 1524918
>utg000267l_pilon_pilon 101 1503815
>utg000138l_pilon_pilon 102 1499363
>utg000182l_pilon_pilon 103 1486386
>utg000188l_pilon_pilon 104 1480645
>utg000079l_pilon_pilon 105 1477904
>utg000199l_pilon_pilon 106 1473787
>utg000242l_pilon_pilon 107 1458654
>utg000190l_pilon_pilon 108 1453399
>utg000197l_pilon_pilon 109 1419366
>utg000342l_pilon_pilon 110 1418713
>utg000166l_pilon_pilon 111 1416522
>utg000018l_pilon_pilon 112 1407967
>utg000160l_pilon_pilon 113 1407966
>utg000204l_pilon_pilon 114 1390906
>utg000046l_pilon_pilon 115 1387684
>utg000144l_pilon_pilon 116 1386713
>utg000087l_pilon_pilon 117 1371939
>utg000282l_pilon_pilon 118 1361927
>utg000100l_pilon_pilon 119 1345730
>utg000014l_pilon_pilon 120 1285199
>utg000326l_pilon_pilon 121 1282553
>utg000120l_pilon_pilon 122 1270722
>utg000236l_pilon_pilon 123 1259940
>utg000127l_pilon_pilon 124 1248169
>utg000158l_pilon_pilon 125 1196370
>utg000021l_pilon_pilon 126 1182355
>utg000050l_pilon_pilon 127 1138983
>utg000025l_pilon_pilon 128 1124907
>utg000337l_pilon_pilon 129 1107141
>utg000083l_pilon_pilon 130 1099890
>utg000201l_pilon_pilon 131 1091340
>utg000126l_pilon_pilon 132 1085465
>utg000006l_pilon_pilon 133 1084794
>utg000330l_pilon_pilon 134 1080327
>utg000320l_pilon_pilon 135 1066649
>utg000184l_pilon_pilon 136 1003655
>utg000186l_pilon_pilon 137 1000012
>utg000063l_pilon_pilon 138 992169
>utg000377l_pilon_pilon 139 958028
>utg000191l_pilon_pilon 140 934040
>utg000279l_pilon_pilon 141 929466
>utg000261l_pilon_pilon:::fragment_1 142 560752
>utg000261l_pilon_pilon:::fragment_2:::debris 143 125000
>utg000261l_pilon_pilon:::fragment_3 144 242648
>utg000039l_pilon_pilon 145 906362
>utg000048l_pilon_pilon 146 901390
>utg000346l_pilon_pilon 147 894715
>utg000231l_pilon_pilon 148 881111
>utg000077l_pilon_pilon 149 874546
>utg000043l_pilon_pilon 150 872087
>utg000177l_pilon_pilon 151 841144
>utg000276l_pilon_pilon 152 836726
>utg000235l_pilon_pilon 153 825114
>utg000303l_pilon_pilon 154 811203
>utg000420l_pilon_pilon 155 807509
>utg000270l_pilon_pilon 156 806069
>utg000124l_pilon_pilon 157 803763
>utg000305l_pilon_pilon 158 749426
>utg000339l_pilon_pilon 159 735773
>utg000363l_pilon_pilon 160 731752
>utg000099l_pilon_pilon 161 729267
>utg000038l_pilon_pilon 162 726832
>utg000143l_pilon_pilon 163 724278
>utg000216l_pilon_pilon 164 722458
>utg000296l_pilon_pilon 165 711523
>utg000269l_pilon_pilon 166 700291
>utg000411l_pilon_pilon 167 669664
>utg000060l_pilon_pilon 168 663149
>utg000308l_pilon_pilon 169 655964
>utg000068l_pilon_pilon 170 651901
>utg000162l_pilon_pilon 171 651779
>utg000262l_pilon_pilon 172 649231
>utg000168l_pilon_pilon 173 647671
>utg000093l_pilon_pilon 174 630409
>utg000089l_pilon_pilon 175 586212
>utg000080l_pilon_pilon 176 585801
>utg000487l_pilon_pilon 177 581165
>utg000128l_pilon_pilon 178 570273
>utg000081l_pilon_pilon 179 562771
>utg000092l_pilon_pilon 180 549257
>utg000165l_pilon_pilon 181 549012
>utg000476l_pilon_pilon 182 546557
>utg000281l_pilon_pilon 183 545268
>utg000338l_pilon_pilon 184 542073
>utg000257l_pilon_pilon 185 541065
>utg000176l_pilon_pilon 186 540736
>utg000076l_pilon_pilon 187 536782
>utg000130l_pilon_pilon 188 532929
>utg000358l_pilon_pilon 189 531685
>utg000260l_pilon_pilon 190 520416
>utg000155l_pilon_pilon 191 519119
>utg000287l_pilon_pilon 192 509670
>utg000419l_pilon_pilon 193 506721
>utg000402l_pilon_pilon 194 499425
>utg000309l_pilon_pilon 195 492527
>utg000172l_pilon_pilon 196 492045
>utg000331l_pilon_pilon 197 488340
>utg000288l_pilon_pilon 198 483892
>utg000323l_pilon_pilon 199 477012
>utg000306l_pilon_pilon 200 475697
>utg000443l_pilon_pilon 201 474049
>utg000065l_pilon_pilon 202 470167
>utg000226l_pilon_pilon 203 455370
>utg000064l_pilon_pilon 204 451868
>utg000118l_pilon_pilon 205 438378
>utg000404l_pilon_pilon 206 431660
>utg000410l_pilon_pilon 207 422671
>utg000045l_pilon_pilon 208 418111
>utg000441l_pilon_pilon 209 417081
>utg000367l_pilon_pilon 210 415316
>utg000030l_pilon_pilon 211 414110
>utg000010l_pilon_pilon 212 409713
>utg000098l_pilon_pilon 213 406997
>utg000213l_pilon_pilon 214 403946
>utg000071l_pilon_pilon 215 389466
>utg000196l_pilon_pilon 216 380445
>utg000085l_pilon_pilon 217 378778
>utg000310l_pilon_pilon 218 376351
>utg000414l_pilon_pilon 219 374211
>utg000469l_pilon_pilon 220 373948
>utg000174l_pilon_pilon 221 367328
>utg000212l_pilon_pilon 222 366135
>utg000379l_pilon_pilon 223 365714
>utg000360l_pilon_pilon 224 356642
>utg000391l_pilon_pilon 225 346976
>utg000243l_pilon_pilon 226 344889
>utg000333l_pilon_pilon 227 331239
>utg000259l_pilon_pilon 228 323962
>utg000486l_pilon_pilon 229 316037
>utg000228l_pilon_pilon 230 312045
>utg000430l_pilon_pilon 231 300221
>utg000244l_pilon_pilon 232 298277
>utg000156l_pilon_pilon 233 296698
>utg000106l_pilon_pilon 234 292596
>utg000396l_pilon_pilon 235 290313
>utg000102l_pilon_pilon 236 284240
>utg000314l_pilon_pilon 237 283642
>utg000361l_pilon_pilon 238 282841
>utg000336l_pilon_pilon 239 282280
>utg000194l_pilon_pilon 240 276731
>utg000481l_pilon_pilon 241 272607
>utg000325l_pilon_pilon 242 272541
>utg000234l_pilon_pilon 243 272264
>utg000271l_pilon_pilon 244 265031
>utg000492l_pilon_pilon 245 264250
>utg000013l_pilon_pilon 246 257616
>utg000383l_pilon_pilon 247 257440
>utg000057l_pilon_pilon 248 256785
>utg000214l_pilon_pilon 249 244643
>utg000151l_pilon_pilon 250 242207
>utg000382l_pilon_pilon 251 236158
>utg000413l_pilon_pilon 252 230105
>utg000398l_pilon_pilon 253 229660
>utg000086l_pilon_pilon 254 229640
>utg000357l_pilon_pilon 255 226929
>utg000219l_pilon_pilon 256 224199
>utg000142l_pilon_pilon 257 223853
>utg000457l_pilon_pilon 258 219566
>utg000343l_pilon_pilon 259 215121
>utg000432l_pilon_pilon 260 214706
>utg000132l_pilon_pilon 261 214388
>utg000179l_pilon_pilon 262 213683
>utg000412l_pilon_pilon 263 212636
>utg000119l_pilon_pilon 264 206712
>utg000428l_pilon_pilon 265 206224
>utg000322l_pilon_pilon:::fragment_1 266 97218
>utg000322l_pilon_pilon:::fragment_2:::debris 267 100558
>utg000461l_pilon_pilon 268 194978
>utg000187l_pilon_pilon 269 194012
>utg000205l_pilon_pilon 270 190756
>utg000311l_pilon_pilon 271 188772
>utg000222l_pilon_pilon 272 188473
>utg000350l_pilon_pilon 273 187234
>utg000362l_pilon_pilon 274 185212
>utg000009l_pilon_pilon 275 182630
>utg000110l_pilon_pilon 276 181550
>utg000318l_pilon_pilon 277 179005
>utg000268l_pilon_pilon 278 176045
>utg000371l_pilon_pilon 279 175059
>utg000263l_pilon_pilon 280 173932
>utg000229l_pilon_pilon 281 173400
>utg000380l_pilon_pilon 282 171357
>utg000302l_pilon_pilon 283 166985
>utg000211l_pilon_pilon 284 166595
>utg000084l_pilon_pilon 285 164282
>utg000369l_pilon_pilon 286 163819
>utg000437l_pilon_pilon 287 155101
>utg000070l_pilon_pilon 288 154694
>utg000129l_pilon_pilon 289 151861
>utg000195l_pilon_pilon 290 148202
>utg000015l_pilon_pilon 291 148099
>utg000150l_pilon_pilon 292 147993
>utg000458l_pilon_pilon 293 147499
>utg000366l_pilon_pilon 294 147422
>utg000354l_pilon_pilon 295 145936
>utg000478l_pilon_pilon 296 144887
>utg000571l_pilon_pilon 297 143456
>utg000167l_pilon_pilon 298 143264
>utg000313l_pilon_pilon 299 142793
>utg000477l_pilon_pilon 300 141613
>utg000169l_pilon_pilon 301 140499
>utg000321l_pilon_pilon 302 137568
>utg000395l_pilon_pilon 303 133853
>utg000368l_pilon_pilon 304 133605
>utg000375l_pilon_pilon 305 133508
>utg000415l_pilon_pilon 306 129434
>utg000040l_pilon_pilon 307 129208
>utg000253l_pilon_pilon 308 129070
>utg000393l_pilon_pilon 309 128615
>utg000225l_pilon_pilon 310 128122
>utg000178l_pilon_pilon 311 126500
>utg000541l_pilon_pilon 312 122677
>utg000023l_pilon_pilon 313 121332
>utg000460l_pilon_pilon 314 119955
>utg000431l_pilon_pilon 315 119345
>utg000533l_pilon_pilon 316 118529
>utg000319l_pilon_pilon 317 118288
>utg000401l_pilon_pilon 318 113853
>utg000291l_pilon_pilon 319 113671
>utg000425l_pilon_pilon 320 112835
>utg000531l_pilon_pilon 321 112693
>utg000122l_pilon_pilon 322 112309
>utg000189l_pilon_pilon 323 111109
>utg000285l_pilon_pilon 324 110747
>utg000416l_pilon_pilon 325 106461
>utg000442l_pilon_pilon 326 104604
>utg000171l_pilon_pilon 327 103754
>utg000423l_pilon_pilon 328 103164
>utg000519l_pilon_pilon 329 102891
>utg000438l_pilon_pilon 330 102208
>utg000247l_pilon_pilon 331 102109
>utg000154l_pilon_pilon 332 101568
>utg000221l_pilon_pilon 333 99880
>utg000387l_pilon_pilon 334 99390
>utg000245l_pilon_pilon 335 99138
>utg000473l_pilon_pilon 336 98814
>utg000505l_pilon_pilon 337 95552
>utg000436l_pilon_pilon 338 95423
>utg000192l_pilon_pilon 339 93609
>utg000482l_pilon_pilon 340 93237
>utg000239l_pilon_pilon 341 92328
>utg000348l_pilon_pilon 342 92254
>utg000504l_pilon_pilon 343 91077
>utg000488l_pilon_pilon 344 91059
>utg000417l_pilon_pilon 345 90849
>utg000381l_pilon_pilon 346 88935
>utg000498l_pilon_pilon 347 88314
>utg000491l_pilon_pilon 348 86995
>utg000131l_pilon_pilon 349 86066
>utg000523l_pilon_pilon 350 85785
>utg000616l_pilon_pilon 351 83218
>utg000567l_pilon_pilon 352 82458
>utg000538l_pilon_pilon 353 82313
>utg000193l_pilon_pilon 354 82290
>utg000536l_pilon_pilon 355 81768
>utg000356l_pilon_pilon 356 81502
>utg000495l_pilon_pilon 357 81308
>utg000453l_pilon_pilon 358 81192
>utg000298l_pilon_pilon 359 80644
>utg000601l_pilon_pilon 360 79905
>utg000450l_pilon_pilon 361 77147
>utg000012l_pilon_pilon 362 76882
>utg000409l_pilon_pilon 363 76545
>utg000324l_pilon_pilon 364 76040
>utg000503l_pilon_pilon 365 75778
>utg000516l_pilon_pilon 366 75713
>utg000266l_pilon_pilon 367 74865
>utg000152l_pilon_pilon 368 74800
>utg000403l_pilon_pilon 369 72936
>utg000278c_pilon_pilon 370 72132
>utg000359l_pilon_pilon 371 71610
>utg000434l_pilon_pilon 372 70899
>utg000277l_pilon_pilon 373 70751
>utg000506l_pilon_pilon 374 68608
>utg000512l_pilon_pilon 375 67904
>utg000240l_pilon_pilon 376 67036
>utg000518l_pilon_pilon 377 64356
>utg000125l_pilon_pilon 378 63590
>utg000355l_pilon_pilon 379 63472
>utg000246l_pilon_pilon 380 61512
>utg000585l_pilon_pilon 381 59548
>utg000468l_pilon_pilon 382 58786
>utg000644l_pilon_pilon 383 58476
>utg000617l_pilon_pilon 384 55554
>utg000237l_pilon_pilon 385 53294
>utg000470l_pilon_pilon 386 51004
>utg000429l_pilon_pilon 387 49851
>utg000352l_pilon_pilon 388 49747
>utg000455l_pilon_pilon 389 45317
>utg000145c_pilon_pilon 390 43825
>utg000153l_pilon_pilon 391 42944
>utg000552l_pilon_pilon 392 41062
>utg000583l_pilon_pilon 393 37229
>utg000385l_pilon_pilon 394 33749
>utg000462c_pilon_pilon 395 33535
>utg000577l_pilon_pilon:::fragment_1:::debris 396 0
>utg000577l_pilon_pilon:::fragment_2 397 29984
>utg000604l_pilon_pilon:::fragment_1:::debris 398 0
>utg000604l_pilon_pilon:::fragment_2:::debris 399 0
>utg000604l_pilon_pilon:::fragment_3 400 29798
>utg000557c_pilon_pilon 401 5738
161 308 370 -394 25 -5 44
46 113 -337 187 47 130 23 -114 92 123
-151 323 -291 214 281 172 358 -175 -140 -351 -311 145 199 229 379 -6 380 147 -146 -268
-272 310 -259 -96 -19 153 -18
-344 22 141 -93 -285 -239 -387 356 263 -115 -155 -95 200 -197
-35 -73 -34 -112 -104 279 -17 -262 203 233 383 320
-327 -256 389 277 302 119 -72 -219 -152 102 231 319 -369 100 137 286 83 343 -106 -362 69 110 -325 -37
53 4 36
-269 270 -59 32 77 -275 195 108 -20 176 -78
346 381 -293 -313 -192 15 -50 298 301 -202 -220 -43 -125 142
144 -129 -303 216 228 331 -121 11 -75 71 -235 -107 -321 -41
-39 -363 -326 225 -357 375 -377 -193 90 185 169 -70 -280 -9 305 209 188 76 -68 -265 182 82 132 -157 -261 -149 168 330 276 1
-314 -309 -297 -241 -296 -118 -170 365 48 127 171 159 184 -353 80 -33 74 84 374
3 109 -38 181 -232 359 -89 -179 -98
386 367 -246 -258 -215 -237 -317 278 -173 333 312 -376 341 393 388 382 361 342 -334 400 -288 283 273 284 349 -391 -255 -254 236 178 -230 257 -392 -88 -166 244 350 -49 163 198 206 -183 117 316 354 366 -315 -177 -364 -191 -339 -264 304 122 -324 -238 -21 31 -180 -29 126 -300 -360 -352 -30 42
-27 116 390 -213 372 355 -335 -289 -186 156 -133 -212 -86 -63 -61 91 -222 348 -294 99 -249 -174 196 -131
226 224 138 -210 -318 139 -260 338 371 -26 -65 245 -67 -150 247 16 87 -190 -252
384 -250 299 -287 368 274 -295 205 -271 -292 55 -329 58 340 -207 14 242 -51 -165 120
111 158 373 -148 -336 -227 124 64 223 7 164 -134 -217
332 -266 243 -154 378 218 -248 211 -201 62 -13 85 54 -79 -251
282 189 -8 306 194 -234 57 -204 -322 -105 -221 -347
-328 -56 81 101 60 66 240 307 290 103
208 24 10 52 -135
-160 -167 12 -94 395 267 385 397 398 399 396 401 128 136 -345 162 253 -97
45
2
-28
143
-40

**Comment by shawnpg** [comment]
Hi Hannah,

Thanks! It looks like there are 3 zero-length contigs in there, so removing those should clear up the error. I have made the necessary edits to the .assembly file and attached them to this message (you might need to remove the .txt extension, which I had to add so GitHub would let me upload it).

Could you let us know if it works for you? If it doesn't, can you also send us the FASTA file so we can try running and debugging the code? That file is probably too big for GitHub, so if it is, send us an email at support@phasegenomics.com to coordinate an upload/download via FTP, Dropbox, Google Drive, or something like that.

Thanks,

Shawn
[ kraken.final.review.cleaned.assembly.txt](https://github.com/phasegenomics/juicebox_scripts/files/6780374/kraken.final.review.cleaned.assembly.txt)

**Comment by Hannah1746** [comment]
Hmmm. That seemed to help but no fix the problem: 

python juicebox_assembly_converter.py -a kraken.final.review.cleaned.assembly -f curated.fasta 
Processing assembly file. Details:
Assembly:			kraken.final.review.cleaned.assembly
Fasta:				curated.fasta
Output prefix:			kraken.final.review.cleaned
Contig mode:			False
Simple Chromosome Names:	False

Reading sequences from curated.fasta...
......
Sequences read

Reading .assembly file kraken.final.review.cleaned.assembly...
Traceback (most recent call last):
  File "juicebox_assembly_converter.py", line 831, in <module>
    processed_assembly = JuiceboxConverter().process(fasta, assembly,
  File "juicebox_assembly_converter.py", line 78, in process
    assembly_map, scaffolds = self._read_assembly(assembly, contig_mode=contig_mode)
  File "juicebox_assembly_converter.py", line 206, in _read_assembly
    index = abs(int(contig)) - 1
ValueError: invalid literal for int() with base 10: 'utg000072l_pilon_pilon:::fragment_1'

**Comment by shawnpg** [comment]
Hi Hannah,

Progress at least. It looks like it made it past the previous place it was erroring, then failed because the contig names don't have a ">" prefix. I've added those prefixes in this file, try again?

Thanks,

Shawn

[ kraken.final.review.cleaned.assembly.txt](https://github.com/phasegenomics/juicebox_scripts/files/6780708/kraken.final.review.cleaned.assembly.txt)

**Comment by shawnpg** [comment]
New assembly file solved the problem.
